additional_services:
- spamoor
- prometheus_grafana
- dora
ethereum_metrics_exporter_enabled: true
participants:
- cl_extra_env_vars: {}
  cl_extra_labels: {}
  cl_extra_params: []
  cl_image: ''
  cl_log_level: ''
  cl_max_cpu: 0
  cl_max_mem: 0
  cl_min_cpu: 0
  cl_min_mem: 0
  cl_tolerations: []
  cl_type: lighthouse
  cl_volume_size: 0
  el_extra_env_vars: {}
  el_extra_labels: {}
  el_extra_params: []
  el_image: ethpandaops/erigon:main
  el_log_level: ''
  el_max_cpu: 0
  el_max_mem: 0
  el_min_cpu: 0
  el_min_mem: 0
  el_tolerations: []
  el_type: erigon
  el_volume_size: 0
  prometheus_config:
    labels: {}
    scrape_interval: 15s
spamoor_params:
  image: ethpandaops/spamoor:latest
  max_pending: 1000
  max_wallets: 20
  scenario: deploy-destruct
  spamoor_extra_args:
  - --amount=20
  - --count=2000
  throughput: 20000
